### PR TITLE
0.6.1

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Note we found an issue with Night Mode, if that is an important feature to you can wait for the 0.6.2 release that should be soon.

### CODE REVIEW

**Comment by lmfurey** [comment]
Jason, Thank you for the pull request.  For some reason I cannot get the Data to go from the dexcom/phone paring to Mongolab.  any suggestions.

**Comment by jasoncalabrese** [comment]
On the uploader phone are all the icons at the bottom green?  What version is the Nightscout Android uploader?  You can find it in the preferences.

**Comment by lmfurey** [comment]
Jason,
We have the Cookie Monster, version 0.1.10.  The icons at the btm of the
app are green except the "upload" one.

**Comment by jasoncalabrese** [comment]
0.1.12 is available now, but the issue is probably unrelated to the
uploader version.

Are you using direct mongo upload or the rest api?  Are you able to use the
browser on the uploader phone?

Is likely that the problem is your mongo or api setting, very easy to make
a typo and hard to find them.

**Comment by lmfurey** [comment]
l think i am using the direct mongo upload.  I double checked the string
and i did find a typo.  once I get her back in range I will hook it back up
and see if that fixed it.
Thanks, I will let you know.

**Pull request merged**
